In [21]:
# Importing the relevant modules
from transformers import BertTokenizer, BertModel, BertForSequenceClassification
import pandas as pd
import numpy as np
import torch
import csv
from tensorflow.keras.layers import Dense
from tensorflow.keras import Sequential

In [2]:
# Load the tokenizer of the "bert-base-cased" pretrained model
# See https://huggingface.co/transformers/pretrained_models.html for other models
tz = BertTokenizer.from_pretrained("bert-base-uncased")

In [27]:
x=pd.read_csv("/home/bruce/EP-M1/ML-DL/Project/train.csv")

In [28]:
x_text=x['text']
x_vect=[]

In [ ]:
for i in x_text:
    sent = i
    encoded = tz.encode_plus(
    text=sent,  # the sentence to be encoded
    add_special_tokens=True,  # Add [CLS] and [SEP]
    max_length = 35,  # maximum length of a sentence
    pad_to_max_length=True,  # Add [PAD]s
    return_attention_mask = True,  # Generate the attention mask
    return_tensors = 'pt',  # ask the function to return PyTorch tensors
    )
    input_ids = encoded['input_ids'] 
    x_vect.append(input_ids)

/home/bruce/.local/lib/python3.10/site-packages/transformers/tokenization_utils_base.py:2336: FutureWarning: The `pad_to_max_length` argument is deprecated and will be removed in a future version, use `padding=True` or `padding='longest'` to pad to the longest sequence in the batch, or use `padding='max_length'` to pad to a max length. In this case, you can give a specific length with `max_length` (e.g. `max_length=45`) or leave max_length to None to pad to the maximal input size of the model (e.g. 512 for Bert).
  warnings.warn(


In [6]:
x_vec=[]
for i in x_vect:
    i = torch.flatten(i)
    i = i.numpy()
    x_vec.append(i)

In [7]:
x_vec

[array([  101, 19387, 25416,  2906,  6895,  2099, 26632,  2078,  2019,
         2015,  2053,  2213,  7374,   102,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0]),
 array([ 101, 3769, 7068, 7442,  102,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0]),
 array([  101,  6904,  4904,  2139,  3654,  4590, 25022,  3070,  2571,
          102,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0]),
 array([  101,  4372, 20240, 27881,  2015,  2777,  7913, 20422,  2015,
         2343, 16360, 12083,  3669,  4226,  6904,  4904, 13675, 26250,
         2343,  2123,  3678,  2558,  2063,  4012, 13876,  2063,  2033,
        28632,  2015,   102]),
 array([  101,  5003,  8873, 10600,  2063, 28558, 26632,  2078

In [8]:
x["tv"]=x_vec

In [9]:
x = x.drop(["text","mentions","urls","hashtags","timestamp","TweetID"],axis=1)

In [10]:
x

retweets_count  favorites_count  followers_count  statuses_count  \
0                    3                0             3682          453535   
1                    0                0               86            1016   
2                    3                1             1944           28234   
3                    0                0                1            1072   
4                    0                0            13957           25311   
...                ...              ...              ...             ...   
353964               0                0               34            1509   
353965               0                0               89           11166   
353966               3                0             1888             712   
353967               0                0              139             486   
353968               0                0                0              82   

        friends_count  verified  \
0                3628         0   
1                 284         0   
2                1995         0   
3                   0         0   
4               10841         0   
...               ...       ...   
353964             55         0   
353965            127         0   
353966           3086         0   
353967            320         0   
353968             24         0   

                                                       tv  
0       [101, 19387, 25416, 2906, 6895, 2099, 26632, 2...  
1       [101, 3769, 7068, 7442, 102, 0, 0, 0, 0, 0, 0,...  
2       [101, 6904, 4904, 2139, 3654, 4590, 25022, 307...  
3       [101, 4372, 20240, 27881, 2015, 2777, 7913, 20...  
4       [101, 5003, 8873, 10600, 2063, 28558, 26632, 2...  
...                                                   ...  
353964  [101, 2175, 2078, 21031, 4674, 2778, 16939, 20...  
353965  [101, 2605, 14542, 10231, 9307, 8557, 4372, 35...  
353966  [101, 4388, 27838, 7382, 8162, 22357, 27514, 2...  
353967  [101, 11721, 15217, 13473, 2015, 6245, 1052, 4...  
353968  [101, 2632, 4590, 2666, 14459, 26632, 2078, 90...  

[353969 rows x 7 columns]

In [13]:
y = pd.read_csv("/home/bruce/EP-M1/ML-DL/Project/evaluation.csv")

In [14]:
y_text=y['text']

In [15]:
y_vect=[]

In [16]:
for i in y_text:
    sent = i
    encoded = tz.encode_plus(
    text=sent,  # the sentence to be encoded
    add_special_tokens=True,  # Add [CLS] and [SEP]
    max_length = 35,  # maximum length of a sentence
    pad_to_max_length=True,  # Add [PAD]s
    return_attention_mask = True,  # Generate the attention mask
    return_tensors = 'pt',  # ask the function to return PyTorch tensors
    )
    input_ids = encoded['input_ids'] 
    y_vect.append(input_ids)

/home/bruce/.local/lib/python3.10/site-packages/transformers/tokenization_utils_base.py:2336: FutureWarning: The `pad_to_max_length` argument is deprecated and will be removed in a future version, use `padding=True` or `padding='longest'` to pad to the longest sequence in the batch, or use `padding='max_length'` to pad to a max length. In this case, you can give a specific length with `max_length` (e.g. `max_length=45`) or leave max_length to None to pad to the maximal input size of the model (e.g. 512 for Bert).
  warnings.warn(


In [17]:
y_vec =[]
for i in y_vect:
    i = torch.flatten(i)
    i = i.numpy()
    y_vec.append(i)

In [18]:
y=y.drop(["mentions","urls","hashtags","text","timestamp"],axis=1)

In [19]:
y["tv"]=y_vec

In [20]:
y

favorites_count  followers_count  statuses_count  friends_count  \
0                     0               85            4442            327   
1                     0              427           33282            443   
2                     6             1127           13111           1596   
3                     2             1699           25760           2036   
4                     0              249           20718            369   
...                 ...              ...             ...            ...   
117985                0                4             194             64   
117986                0              744           39489            894   
117987               12              924            2270            159   
117988                0                5               4             80   
117989                0              555            5703            149   

        verified  TweetID                                                 tv  
0              0  1184643  [101, 18855, 5657, 10364, 13013, 4270, 3789, 1...  
1              0  1199190  [101, 6302, 5157, 2063, 12098, 13578, 4962, 23...  
2              0   917372  [101, 9998, 20236, 2015, 20877, 2483, 2695, 20...  
3              0   731754  [101, 8840, 2140, 25222, 6904, 4904, 2117, 277...  
4              0  1400049  [101, 27838, 7382, 8162, 2404, 8113, 12532, 92...  
...          ...      ...                                                ...  
117985         0   192729  [101, 21451, 2483, 1999, 10288, 7874, 3085, 37...  
117986         0   445763  [101, 21451, 7054, 2102, 9680, 8945, 12190, 95...  
117987         0   423814  [101, 13012, 13473, 2613, 4221, 2522, 17258, 1...  
117988         0  1220017  [101, 6581, 2063, 8909, 4402, 13433, 22909, 24...  
117989         0   997494  [101, 19387, 17995, 2480, 5312, 15421, 14916, ...  

[117990 rows x 7 columns]

In [22]:
bert_model = BertForSequenceClassification.from_pretrained('bert-base-uncased')

Some weights of the model checkpoint at bert-base-uncased were not used when initializing BertForSequenceClassification: ['cls.seq_relationship.bias', 'cls.predictions.transform.dense.weight', 'cls.predictions.transform.dense.bias', 'cls.predictions.transform.LayerNorm.weight', 'cls.predictions.transform.LayerNorm.bias', 'cls.predictions.decoder.weight', 'cls.seq_relationship.weight', 'cls.predictions.bias']
- This IS expected if you are initializing BertForSequenceClassification from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing BertForSequenceClassification from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).
Some weights of BertForSequenceClassification were not initialized from the model checkpoint at

In [23]:
bert_model

BertForSequenceClassification(
  (bert): BertModel(
    (embeddings): BertEmbeddings(
      (word_embeddings): Embedding(30522, 768, padding_idx=0)
      (position_embeddings): Embedding(512, 768)
      (token_type_embeddings): Embedding(2, 768)
      (LayerNorm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)
      (dropout): Dropout(p=0.1, inplace=False)
    )
    (encoder): BertEncoder(
      (layer): ModuleList(
        (0): BertLayer(
          (attention): BertAttention(
            (self): BertSelfAttention(
              (query): Linear(in_features=768, out_features=768, bias=True)
              (key): Linear(in_features=768, out_features=768, bias=True)
              (value): Linear(in_features=768, out_features=768, bias=True)
              (dropout): Dropout(p=0.1, inplace=False)
            )
            (output): BertSelfOutput(
              (dense): Linear(in_features=768, out_features=768, bias=True)
              (LayerNorm): LayerNorm((768,), eps=1e-12, element

In [24]:
X = x[["favorites_count","followers_count","statuses_count","friends_count","verified"]]
X = pd.concat([X,x["tv"]])

In [25]:
X

favorites_count  followers_count  statuses_count  friends_count  \
0                   0.0           3682.0        453535.0         3628.0   
1                   0.0             86.0          1016.0          284.0   
2                   1.0           1944.0         28234.0         1995.0   
3                   0.0              1.0          1072.0            0.0   
4                   0.0          13957.0         25311.0        10841.0   
...                 ...              ...             ...            ...   
353964              NaN              NaN             NaN            NaN   
353965              NaN              NaN             NaN            NaN   
353966              NaN              NaN             NaN            NaN   
353967              NaN              NaN             NaN            NaN   
353968              NaN              NaN             NaN            NaN   

        verified                                                  0  
0            0.0                                                NaN  
1            0.0                                                NaN  
2            0.0                                                NaN  
3            0.0                                                NaN  
4            0.0                                                NaN  
...          ...                                                ...  
353964       NaN  [101, 2175, 2078, 21031, 4674, 2778, 16939, 20...  
353965       NaN  [101, 2605, 14542, 10231, 9307, 8557, 4372, 35...  
353966       NaN  [101, 4388, 27838, 7382, 8162, 22357, 27514, 2...  
353967       NaN  [101, 11721, 15217, 13473, 2015, 6245, 1052, 4...  
353968       NaN  [101, 2632, 4590, 2666, 14459, 26632, 2078, 90...  

[707938 rows x 6 columns]

In [26]:
Y = x["retweets_count"]

In [48]:
# Set the model's hyperparameters
learning_rate = 3e-5
batch_size = 8
num_epochs = 100

# Create the neural network model
model = Sequential()
model.add(Dense(1))
model.add(Dense(1))
model.add(Dense(1))

# Compile and train the model
model.compile(
    optimizer='adam',
    loss='MeanAbsoluteError'
)
model.fit(
    X, Y,
    batch_size=batch_size,
    epochs=num_epochs
)

# Use the trained model to make predictions
predictions = model.predict(X)

Epoch 1/100
44247/44247 [==============================] - 36s 804us/step - loss: 254.8986
Epoch 2/100
44247/44247 [==============================] - 36s 804us/step - loss: 10.8761
Epoch 3/100
44247/44247 [==============================] - 37s 835us/step - loss: 10.0451
Epoch 4/100
44247/44247 [==============================] - 38s 853us/step - loss: 9.7594
Epoch 5/100
44247/44247 [==============================] - 36s 805us/step - loss: 9.4796
Epoch 6/100
44247/44247 [==============================] - 36s 804us/step - loss: 9.3069
Epoch 7/100
44247/44247 [==============================] - 36s 805us/step - loss: 9.1751
Epoch 8/100
44247/44247 [==============================] - 36s 806us/step - loss: 9.1366
Epoch 9/100
44247/44247 [==============================] - 35s 802us/step - loss: 9.0000
Epoch 10/100
44247/44247 [==============================] - 35s 798us/step - loss: 8.9438
Epoch 11/100
44247/44247 [==============================] - 35s 801us/step - loss: 8.8158
Epoch 12/100
44

44247/44247 [==============================] - 36s 803us/step - loss: 8.4324
Epoch 93/100
44247/44247 [==============================] - 36s 806us/step - loss: 8.4025
Epoch 94/100
44247/44247 [==============================] - 36s 803us/step - loss: 8.4875
Epoch 95/100
44247/44247 [==============================] - 36s 807us/step - loss: 8.4833
Epoch 96/100
44247/44247 [==============================] - 35s 802us/step - loss: 8.4594
Epoch 97/100
44247/44247 [==============================] - 36s 810us/step - loss: 8.4063
Epoch 98/100
44247/44247 [==============================] - 36s 815us/step - loss: 8.4960
Epoch 99/100
44247/44247 [==============================] - 36s 809us/step - loss: 8.4279
Epoch 100/100
11062/11062 [==============================] - 7s 644us/step


In [94]:
z=y[["favorites_count","followers_count","statuses_count","friends_count","verified"]]

In [92]:
z = pd.concat([z,y["tv"]])

In [97]:
model.predict(z)

3688/3688 [==============================] - 2s 629us/step


array([[4.1749757e-02],
       [1.5789021e-02],
       [1.6728985e+00],
       ...,
       [2.7862463e+00],
       [1.2437119e-03],
       [2.2165347e-02]], dtype=float32)

In [98]:
pr = model.predict(z)

3688/3688 [==============================] - 2s 601us/step


In [110]:
test = pd.read_csv("/home/bruce/EP-M1/ML-DL/Project/evaluation.csv")

In [114]:
with open("aw1.csv", 'w') as f:
    writer = csv.writer(f)
    writer.writerow(["TweetID", "retweets_count"])
    for index, prediction in enumerate(pr):
        writer.writerow([str(test['TweetID'].iloc[index]) , str(int(prediction))])
